      - name: Upload artifact
        run: |
          zip -r macOS-App.zip dist/
        shell: bash
      - name: Upload artifact using curl
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @macOS-App.zip \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.run_id }}/assets?name=macOS-App.zip"